/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Titanium SDK
 * Copyright TiDev, Inc. 04/07/2022-Present
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */
package ti.scandit;

import com.scandit.datacapture.barcode.data.Symbology;
import com.scandit.datacapture.core.source.ScanIntention;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;


@Kroll.module(name = "TiScandit", id = "ti.scandit")
public class TiScanditModule extends KrollModule {

    // Standard Debugging variables


    @Kroll.constant public static final int EAN13UPCA = 0;
    @Kroll.constant public static final int Code128 = 1;
    @Kroll.constant public static final int Code39 = 2;
    @Kroll.constant public static final int QR = 3;
    @Kroll.constant public static final int EAN8 = 4;
    @Kroll.constant public static final int UPCE = 5;

    @Kroll.constant
    public static final int OFF = 0;
    @Kroll.constant
    public static final int ON = 1;

    @Kroll.constant
    public static final int MANUAL = 0;
    @Kroll.constant
    public static final int SMART = 1;



    public TiScanditModule() {
        super();
    }

    @Kroll.onAppCreate
    public static void onAppCreate(TiApplication app) {
    }


}

